version: "1"
services:
  - type: web
    name: lottery-bot-prod
    runtime: python
    region: singapore
    plan: free
    repo: https://github.com/dawita19/Lottory
    autoDeploy: true
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -c "from main import init_db; init_db()"
    startCommand: gunicorn --bind :$PORT --workers 1 --threads 2 --timeout 0 main:bot.run
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: CHANNEL_ID
        sync: false
    healthCheckPath: /health
    disk:
      name: lottery_data
      mountPath: /data
      sizeGB: 1
