services:
  - type: web
    name: lottery-bot-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind :$PORT --workers 1 --threads 2 --timeout 0 main:app
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromGroup: lottery-bot-secrets
      - key: TELEGRAM_BOT_TOKEN
        fromGroup: lottery-bot-secrets
      - key: ADMIN_IDS
        fromGroup: lottery-bot-secrets
      - key: CHANNEL_ID
        fromGroup: lottery-bot-secrets

  - type: worker
    name: lottery-bot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py --worker
    envVars:
      - key: DATABASE_URL
        fromGroup: lottery-bot-secrets
      - key: TELEGRAM_BOT_TOKEN
        fromGroup: lottery-bot-secrets
      - key: ADMIN_IDS
        fromGroup: lottery-bot-secrets
      - key: CHANNEL_ID
        fromGroup: lottery-bot-secrets
